name: Continous integration
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0

